### ISSUE TITLE
Shell.Interactive should not run availableTestCommands

### ISSUE THREAD

**Issue by jaredrummler** [Chainfire/libsuperuser#32]
When creating an interactive shell the [`Shell.availableTestCommands`](https://github.com/Chainfire/libsuperuser/blob/master/libsuperuser/src/eu/chainfire/libsuperuser/Shell.java#L201-204) are run *after* the initial commands. This will only happen if the `onCommandResultListener` is not null.

TEST:

```java
new Thread() {
  @Override
  public void run() {
      String[] commands = {
              "echo foo",
              "sleep 1",
              "echo bar",
              "sleep 1",
              "echo baz"
      };

      new Shell.Builder()
      .setShell("sh")
      .setOnSTDOUTLineListener(new Shell.OnCommandLineListener() {

        @Override
        public void onLine(String line) {
            android.util.Log.d("ShellTest", line);
        }

        @Override
        public void onCommandResult(int commandCode, int exitCode) {
            
        }
    })
    .addCommand(commands)
    .open(new Shell.OnCommandResultListener() {
        
        @Override
        public void onCommandResult(int commandCode, int exitCode, List<String> output) {
            android.util.Log.d("ShellTest", String.format("finished with exit code %d", exitCode));
        }
    });
  }
}.start();
```

LOG:
```
D/ShellTest(10309): foo
D/ShellTest(10309): bar
D/ShellTest(10309): baz
D/ShellTest(10309): -BOC-
D/ShellTest(10309): uid=10177(u0_a177) gid=10177(u0_a177) groups=1015(sdcard_rw),1028(sdcard_r),3003(inet),9997(everybody),50177(all_a177) context=u:r:untrusted_app:s0
D/ShellTest(10309): finished with exit code 0
```
___

If the interactive shell is opened with commands then the [attempt to give time for the dialog to show](https://github.com/Chainfire/libsuperuser/blob/master/libsuperuser/src/eu/chainfire/libsuperuser/Shell.java#L1041-1056) will be useless.

**Comment by Chainfire** [comment]
While you are absolutely correct that the `availableTestCommands` are run at the wrong time (and I'll commit the fix for that when we're done talking here) if commands are added to the builder, the title of this issue makes me wonder what exactly you are after.

The title states that `availableTestCommands` should not be run at all. What makes you say that? The idea for attaching an `OnCommandResultListener` to the `open` call is getting a callback telling you if the shell was opened correctly or not. If you are looking to get the `exitCode` and output of the `commands` you're executing, you should attach an `OnCommandResultListener` to the `addCommand` call instead of the `open` call.

Please clarify.

**Comment by jaredrummler** [comment]
You are correct. The title was misleading. It was a late night. :)

**Comment by jaredrummler** [comment]
Thanks for the quick fix. I see it would be best to add the `OnCommandResultListener` to the `addCommand` call. Something you might want to consider though is not sending `onLine` results for `availableTestCommands` as that is something the caller would not be expecting.
